[workspace]
members = [
    "cargo-cartesi",
    "cartesi-macros",
    "cartesi-rollups",
    "cartesi-rollups-linux",
    "cartesi-rollups-test",
    "cartesi-rollups-test-doubles",
    "cartesi-rollups-evm-utils",
    "stoopid",
]
