[workspace]
members = [
    "cargo-cartesi",
    "cartesi-rollups",
    "cartesi-rollups-bindings",
    "cartesi-rollups-evm-utils",
    "cartesi-rollups-linux",
    "cartesi-rollups-test",
    "examples/echo",
    "examples/one-shot",
]
