[workspace]
members = [
    "cargo-cartesi",
    "cartesi-macros",
    "cartesi-rollups",
    "cartesi-rollups-linux",
    "cartesi-rollups-linux-test",
    "cartesi-rollups-test",
    "cartesi-rollups-evm-utils",
]
