[package]
name = "stoopid"
version = "0.1.0"
edition = "2021"

[dependencies]
cartesi-rollups-dapp = { path = "../cartesi-rollups-dapp" }
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
env_logger = "0.9.1"
hyper = "0.14.20"
